ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

AVR_USE_MINIMAL_PRINTF = yes

OLED_ENABLE = yes
CONSOLE_ENABLE = no

MIRYOKU_ALPHAS=QWERTY
MIRYOKU_EXTRA=COLEMAKDH
MIRYOKU_TAP=QWERTY
MIRYOKU_NAV=INVERTEDT
MIRYOKU_CLIPBOARD=WIN
MIRYOKU_LAYERS=FLIP
